language: cpp


compiler:
  - gcc


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq


install:
  # install gcc-5 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90

  # Install newer boost compatible with gcc 5.
  - BOOST_VERSION="1.58.0"
  - travis_wait 30 wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=filesystem,system,iostreams,test)
  - (cd $BOOST_ROOT; ./b2 threading=multi --prefix=$BOOST_ROOT -d0 install)

  # install cmake
  - CMAKE_VERSION="3.5.1"
  - wget "http://www.cmake.org/files/v3.5/cmake-${CMAKE_VERSION}.tar.gz"
  - openssl sha1 "cmake-${CMAKE_VERSION}.tar.gz"
  - tar xf "cmake-${CMAKE_VERSION}.tar.gz"
  - cd "cmake-${CMAKE_VERSION}"
  - ./bootstrap --prefix=~
  - make
  - make install
  - export PATH="~/bin:${PATH}"
  - cd ..

  # verify installed versions
  - which cmake
  - cmake --version
  - which g++
  - g++ -v

  # Instal dependencies.
  - sudo apt-get install libboost-dev libboost-filesystem-dev


script:
  - mkdir build
  - cd build
  - ~/bin/cmake .. -DBOOST_ROOT=$BOOST_ROOT -DCMAKE_INSTALL_PREFIX:PATH=~
  - make
  - ./bin/bvh-parser-test


notifications:
  email:
    on_success: false
    on_failure: true